// Generated by gencpp from file cassie_common_toolbox/cassie_velocity_estimation_msg.msg
// DO NOT EDIT!


#ifndef CASSIE_COMMON_TOOLBOX_MESSAGE_CASSIE_VELOCITY_ESTIMATION_MSG_H
#define CASSIE_COMMON_TOOLBOX_MESSAGE_CASSIE_VELOCITY_ESTIMATION_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>

namespace cassie_common_toolbox
{
template <class ContainerAllocator>
struct cassie_velocity_estimation_msg_
{
  typedef cassie_velocity_estimation_msg_<ContainerAllocator> Type;

  cassie_velocity_estimation_msg_()
    : header()
    , linear_velocity()  {
    }
  cassie_velocity_estimation_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , linear_velocity(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_velocity_type;
  _linear_velocity_type linear_velocity;





  typedef boost::shared_ptr< ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator> const> ConstPtr;

}; // struct cassie_velocity_estimation_msg_

typedef ::cassie_common_toolbox::cassie_velocity_estimation_msg_<std::allocator<void> > cassie_velocity_estimation_msg;

typedef boost::shared_ptr< ::cassie_common_toolbox::cassie_velocity_estimation_msg > cassie_velocity_estimation_msgPtr;
typedef boost::shared_ptr< ::cassie_common_toolbox::cassie_velocity_estimation_msg const> cassie_velocity_estimation_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator1> & lhs, const ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.linear_velocity == rhs.linear_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator1> & lhs, const ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cassie_common_toolbox

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76a38944cc7b4b7cc6e1dde51ece2158";
  }

  static const char* value(const ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76a38944cc7b4b7cULL;
  static const uint64_t static_value2 = 0xc6e1dde51ece2158ULL;
};

template<class ContainerAllocator>
struct DataType< ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cassie_common_toolbox/cassie_velocity_estimation_msg";
  }

  static const char* value(const ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header                header\n"
"geometry_msgs/Vector3 linear_velocity\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.linear_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cassie_velocity_estimation_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cassie_common_toolbox::cassie_velocity_estimation_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "linear_velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CASSIE_COMMON_TOOLBOX_MESSAGE_CASSIE_VELOCITY_ESTIMATION_MSG_H
